# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: silverred
description:  A custom Fedora Silverblue bootable OCI image made with BlueBuild
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42
modules:
  - from-file: common/silverblue-main.yml