name: Build images with BlueBuild
on:
  schedule:
    - cron: "00 06 * * *"
  push:
    paths-ignore:
      - "**.md"
      
  pull_request:
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build silverred
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.8.1
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
